#!/usr/bin/env bash

########################################
# QUICK START: vLLM HTTP 化适配
# 快速开始指南和示例脚本
########################################

# 本脚本演示如何使用新的 vLLM HTTP 化方案

set -euo pipefail

echo "========== vLLM HTTP 化适配 - 快速开始 =========="
echo ""
echo "新增文件："
echo "  1. skill_src/vllm_http_client.py"
echo "     → HTTP 客户端：通过 OpenAI API 调用远程 vLLM server"
echo ""
echo "  2. skill_src/solver_offline_rollout_http_client.py"
echo "     → FastAPI 代理层：替代原有 solver_offline_rollout_server.py"
echo ""
echo "  3. skill_src/start_vllm_http_servers.sh"
echo "     → bash 启动脚本：启动多个 vLLM OpenAI API servers"
echo ""
echo "  4. VLLM_HTTP_INTEGRATION.md"
echo "     → 完整集成文档"
echo ""

echo "========== 使用示例 =========="
echo ""
echo "【场景 1】调试模式（3 个 Terminal）"
echo ""
echo "Terminal 1 - 启动 vLLM servers:"
echo "  cd /home/ycy/sdi/Skill_Evo"
echo "  bash skill_src/start_vllm_http_servers.sh 0,1 /path/to/Qwen3-4B-Base"
echo ""
echo "Terminal 2 - 启动代理层:"
echo "  cd /home/ycy/sdi/Skill_Evo"
echo "  export VLLM_HTTP_SERVER_URLS='http://127.0.0.1:8760,http://127.0.0.1:8761'"
echo "  export ROLLOUT_SERVER_MODEL='/path/to/Qwen3-4B-Base'"
echo "  python -m skill_src.solver_offline_rollout_http_client --port 8762"
echo ""
echo "Terminal 3 - 运行 driver:"
echo "  cd /home/ycy/sdi/Skill_Evo"
echo "  python -m skill_src.solver_offline_driver run \\"
echo "    --data-files /path/to/data.jsonl \\"
echo "    --steps 100 --batch-size 8 \\"
echo "    --work-dir /tmp/rollout_work \\"
echo "    --merge-output-dir /tmp/merged"
echo ""

echo "【场景 2】集成到 Synthesizer.sh"
echo ""
echo "在 Synthesizer.sh 中替换原来的 start_rollout_servers.sh 调用："
echo ""
echo "  # 步骤 1: 启动 vLLM HTTP servers（纯 vLLM）"
echo "  bash \"\${SCRIPT_DIR}/../start_vllm_http_servers.sh\" \\"
echo "    \"\${ROLLOUT_GPU_IDS}\" \"\${solver_model_path}\" &"
echo "  VLLM_SERVERS_PID=\$!"
echo ""
echo "  # 步骤 2: 启动代理层（FastAPI，含业务逻辑）"
echo "  export VLLM_HTTP_SERVER_URLS=\"\$(bash -c '"
echo "    IFS=,; arr=(\${ROLLOUT_GPU_IDS}); "
echo "    for i in \${!arr[@]}; do "
echo "      echo -n \"http://127.0.0.1:\$((ROLLOUT_BASE_PORT + i))\"; "
echo "      [ \$i -lt \$((\\${#arr[@]} - 1)) ] && echo -n \",\"; "
echo "    done"
echo "  ')\""
echo "  export ROLLOUT_SERVER_MODEL=\"\${solver_model_path}\""
echo "  python -m skill_src.solver_offline_rollout_http_client \\"
echo "    --port 8762 &"
echo "  ROLLOUT_PROXY_PID=\$!"
echo ""
echo "  # 步骤 3: 等待服务就绪后继续原流程"
echo "  for ((i=0; i<N_ROLLOUT_SERVERS; i++)); do"
echo "    port=\$((ROLLOUT_BASE_PORT + i))"
echo "    wait_for_port \$port 300  # 等待 vLLM 就绪"
echo "  done"
echo "  wait_for_port 8762 300  # 等待代理层就绪"
echo ""

echo "========== 关键改动 =========="
echo ""
echo "无需修改的文件："
echo "  ✓ solver_offline_driver.py - 完全兼容"
echo "  ✓ reward_manager.py - 不涉及 reward 部分"
echo "  ✓ skill_src/Zero/ - 所有 bash 脚本无需改动"
echo "  ✓ 所有其他业务逻辑文件"
echo ""
echo "完全新增的文件："
echo "  + skill_src/vllm_http_client.py"
echo "  + skill_src/solver_offline_rollout_http_client.py"
echo "  + skill_src/start_vllm_http_servers.sh"
echo ""

echo "========== 配置参数 =========="
echo ""
echo "start_vllm_http_servers.sh 环境变量："
echo "  BASE_PORT=8760              (第一个 server 端口)"
echo "  API_KEY=...                 (vllm serve API key)"
echo "  DTYPE=auto                  (推理精度)"
echo "  WAIT_TIMEOUT=180            (健康检查超时)"
echo "  TENSOR_PARALLEL_SIZE=1      (分布式推理)"
echo "  SERVED_MODEL_NAME=default   (对外模型名)"
echo ""
echo "solver_offline_rollout_http_client 环境变量："
echo "  VLLM_HTTP_SERVER_URLS=...   (vLLM server URLs，逗号分隔)"
echo "  ROLLOUT_SERVER_MODEL=...    (模型路径)"
echo "  VLLM_HTTP_TIMEOUT=300.0     (HTTP 超时)"
echo "  VLLM_HTTP_MAX_RETRIES=3     (重试次数)"
echo ""

echo "========== 详细文档 =========="
echo ""
echo "完整的集成文档请查看："
echo "  VLLM_HTTP_INTEGRATION.md"
echo ""
echo "包含以下内容："
echo "  - 详细的架构说明"
echo "  - 多种使用场景"
echo "  - 配置示例"
echo "  - 故障排查"
echo "  - 性能调优建议"
echo ""
