import re
import json
import random
import requests
from tenacity import retry, stop_after_attempt, wait_fixed
import os
import pandas as pd

system="""# TASK: REAL VS. SYNTHETIC QUESTION DETECTION

You are an expert in Computational Linguistics and AI-generated text analysis.  
Your task is to analyze two provided questions and determine which one is a **Real-World Question** (written by a human) and which is a **Synthetic Question** (generated by an AI/LLM).

When producing your answer:
1. Provide a clear, step-by-step analysis explaining your reasoning.
2. Then output a final structured JSON object with exactly these keys:
   - "real_world_question": value must be either "B" or "A"
   - "synthetic_question": value must be either "B" or "A"
   - "confidence_score": numeric (float) between 0.0 (no confidence) and 1.0 (absolute certainty)
   The “confidence_score” reflects how confident you are that the classification (real vs synthetic) is correct.

Important constraints:
- real_world_question and synthetic_question MUST NOT be the same.
- confidence_score MUST be a numeric float between 0.0 and 1.0.
- The JSON object must be the last thing in the response and must appear alone (no surrounding text, no markdown).
- Ensure the last character of the response is the final closing brace '}' (no trailing text or whitespace).
- Do NOT include any other fields or commentary after the JSON.


Example of the required JSON (model should match this format exactly):
{
  "real_world_question": ,
  "synthetic_question": ,
  "confidence_score":
}
"""


user="""
## QUESTIONS FOR ANALYSIS

**Question A:**  
{questionA}

**Question B:**  
{questionB}

Please provide a brief Step-by-Step Analysis(optional), then output the Final JSON object exactly as specified in the system prompt.
"""


api_urls=['https://fast.ominiai.cn/v1/chat/completions']
api_keys=['sk-m7dpHEcWQkQlgoRuOm9S0mYeurwC9BTMpmLnXDrpPOmmkn98','sk-Lplron1sCtErNjSaUDxhgwFuwCyjGKfwJpa9cwFNXcJsMNyB']

@retry(stop=stop_after_attempt(3), wait=wait_fixed(5)) 
def process_example(qA, qB):
    try:
        example = {
            "model": "gpt-4o",
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user.format(
                  questionA=qA,
                  questionB=qB
                )}
            ],
            "temperature": 0.1,

        }
        api_index = random.randint(0, len(api_urls)-1)
        key_index = random.randint(0, len(api_keys)-1)
        api_url = api_urls[api_index]
        api_key = api_keys[key_index]
        gpt_response = requests.post(api_url, headers={"Authorization": f'Bearer {api_key}',"Content-Type": "application/json"}, json=example, timeout=20)
        return gpt_response.json()['choices'][0]['message']['content']
    except Exception as e:
        print(e)
        return None

# LLM 判断正确，reward = max(0, 1 - conf)
# LLM 判断错误，reward = max(0, min(1, conf))

def extract_and_validate(text):

   """
   优先尝试 JSON 提取，如果失败则 fallback 正则提取
   """
   # 1. 尝试 JSON 提取
   m = re.search(r"(\{[\s\S]*\})\s*$", text)
   if m:
      try:
         obj = json.loads(m.group(1))
         rw = obj["real_world_question"]
         sy = obj["synthetic_question"]
         conf = float(obj["confidence_score"])
         # 校验字段合法性
         if rw in ("A","B") and sy in ("A","B") and rw != sy and 0.0 <= conf <= 1.0:
               return {"real": rw, "synthetic": sy, "confidence": round(conf,4)}
      except:
         pass  # 如果 JSON 解析失败，进入 fallback

   # 2. fallback 正则
   # 尝试匹配 "Real-World Question: A" 等格式
   rw_match = re.search(r"real[-_\s]*world[-_\s]*question['\":\- ]+([AB])", text, re.IGNORECASE)
   sy_match = re.search(r"synthetic[-_\s]*question['\":\- ]+([AB])", text, re.IGNORECASE)
   conf_match = re.search(r"confidence[_\s\-:]*([0-9]*\.?[0-9]+)", text, re.IGNORECASE)
   
   rw = rw_match.group(1).upper() if rw_match else None
   sy = sy_match.group(1).upper() if sy_match else None
   conf = float(conf_match.group(1)) if conf_match else 0.5  # fallback 默认值

   # 保证 A/B 和不重复
   if rw not in ("A","B") or sy not in ("A","B") or rw==sy:
      rw, sy = ("A","B") if random.random()>0.5 else ("B","A")
   
   conf = max(0.0, min(1.0, conf))  # 确保置信度在 0~1

   return {"real": rw, "synthetic": sy, "confidence": round(conf,4),'response':text}


def detect_real_vs_synthetic(qA, qB):
   """
   # LLM 判断正确，reward = max(0, 1 - conf)
   # LLM 判断错误，reward = max(0, min(1, conf))
   调用 LLM 判断 Question A/B 谁是真实，谁是合成
   :param qA: Question A 文本  虚假问题
   :param qB: Question B 文本  真实问题
   :param correct_real: 可选，实际真实题，用于计算 reward
   :return: dict {"real": "A/B", "synthetic": "A/B", "confidence": float, "reward": float or None}

   """
   reward = 0.0
   output_text = process_example(qA, qB)
   if output_text:
      result = extract_and_validate(output_text)
      realQ=result['real'].lower()
      syQ=result['synthetic'].lower()
      conf=float(result['confidence'])
      if 'a' in realQ and 'b' in syQ: # 判断错误
         reward=max(0, min(1, conf))
         #reward=max(0, 1-conf)
      elif 'b' in realQ and 'a' in syQ: 
         #reward=max(0, min(1, conf))
         reward=max(0, 1-conf)
   result["reward"] = reward
   return result

def read_data(path):
   if not os.path.exists(path):
      raise ValueError(f'{path} not exist')
   if path.endswith('.jsonl'):
      data = pd.read_json(path,lines=True).to_dict(orient='records')
   elif path.endswith('.parquet'):
      data = pd.read_parquet(path).to_dict(orient='records')
   elif path.endswith('.json'):
      with open(path, 'r') as f:
         data=json.load(f)
   else:
      raise ValueError(f"file type {path.split('.')[-1]} not support!")

   return data
def main(args):
   real_data_path, sy_data_path=args
   real_data = read_data(real_data_path)
   sy_data = read_data(sy_data_path)
   n=10
   real_q = [example['extra_info']['problem'] for example in real_data]
   sy_q = [example['extra_info']['question'] for example in sy_data]
   real_qN=len(real_q)
   sy_qN=len(sy_q)
   real_q1 = random.sample(real_q[:(real_qN//2)],k=n)
   sy_q1 = random.sample(sy_q[:(sy_qN//2)],k=n)
   real_q2 = random.sample(real_q[(real_qN//2):],k=n)
   sy_q2 = random.sample(sy_q[(sy_qN//2):],k=n)
   
   res1=[]
   for qa, qb in zip(sy_q1,real_q1):
      res1.append(detect_real_vs_synthetic(qa, qb))
   with open('false_true_demo.jsonl','w', encoding='utf-8') as f:
      for r in res1:
         f.write(json.dumps(r,ensure_ascii=False) + '\n')
   
   
   res2=[]
   for qa, qb in zip(sy_q1, sy_q2):
      res2.append(detect_real_vs_synthetic(qa, qb))
   with open('false_false_demo.jsonl','w', encoding='utf-8') as f:
      for r in res2:
         f.write(json.dumps(r,ensure_ascii=False) + '\n')
   
   
   res3=[]
   for qa, qb in zip(real_q1, real_q2):
      res3.append(detect_real_vs_synthetic(qa, qb))
   with open('true_true_demo.jsonl','w', encoding='utf-8') as f:
      for r in res3:
         f.write(json.dumps(r,ensure_ascii=False) + '\n')


if __name__ == '__main__':
   real_data_path_dir='/root/users/ycy/data'
   sy_data_path='/root/users/ycy/saved_results/Solver/RRR-Zero_Qwen3-4B-Base-V1/train_data.jsonl'
   real_data_path=os.path.join(real_data_path_dir,'DeepScaleR-40K.parquet')
   main((real_data_path, sy_data_path))
   




   
   