#!/usr/bin/env bash
# Shared defaults for EvolveR math data prep, services, and training.
# Override any variable before invoking a script if needed.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EVOR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$EVOR/../.." && pwd)"

export PYTHONPATH="${REPO_ROOT}:${EVOR}:${PYTHONPATH:-}"

# Experiment naming / output layout
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-deepmath-evolver-rl}"
export WAND_PROJECT="${WAND_PROJECT:-EvolveR-Math}"
export OUTPUT_ROOT="${OUTPUT_ROOT:-$EVOR/outputs}"
export CKPTS_DIR="${CKPTS_DIR:-$OUTPUT_ROOT/ckpts}"
export EXPERIENCE_EXPORT_DIR="${EXPERIENCE_EXPORT_DIR:-$OUTPUT_ROOT/experience_runs}"
export VDB_BASE_DIR="${VDB_BASE_DIR:-$OUTPUT_ROOT/milvus_work}"

# Dataset paths
export DEEPMATH_JSONL="${DEEPMATH_JSONL:-/home/ycy/sdi/data/DeepMath-103K.jsonl}"
export OUT_TRAIN="${OUT_TRAIN:-$OUTPUT_ROOT/deepmath_rl_train.parquet}"
export OUT_VAL="${OUT_VAL:-$OUTPUT_ROOT/deepmath_rl_val.parquet}"
export TRAIN_FILE="${TRAIN_FILE:-$OUT_TRAIN}"
export VAL_FILE="${VAL_FILE:-$OUT_VAL}"
export START="${START:-0}"
export END="${END:-25600}"
export VAL_RATIO="${VAL_RATIO:-0.05}"

# Model / serving defaults
export MODEL_PATH="${MODEL_PATH:-/home/ycy/sdi/models/Qwen3-4B-Instruct-2507}"
export EMBED_MODEL_PATH="${EMBED_MODEL_PATH:-/home/ycy/sdi/models/Qwen3-Embedding-0.6B}"
export EMBEDDING_MODEL="${EMBEDDING_MODEL:-Qwen3-Embedding-0.6B}"
export EMBEDDING_MODEL_NAME="${EMBEDDING_MODEL_NAME:-$EMBEDDING_MODEL}"
export SERVED_NAME="${SERVED_NAME:-$EMBEDDING_MODEL}"
export EMBED_PORT="${EMBED_PORT:-8081}"
export EMBEDDING_API_URL="${EMBEDDING_API_URL:-http://127.0.0.1:${EMBED_PORT}/v1}"
export EMBEDDING_API_KEY="${EMBEDDING_API_KEY:-empty}"
export EMBED_CUDA="${EMBED_CUDA:-0}"
export GPU_NUM="${GPU_NUM:-1}"
export EMBED_GPU_MEM_UTIL="${EMBED_GPU_MEM_UTIL:-0.15}"
export EMBED_MAX_MODEL_LEN="${EMBED_MAX_MODEL_LEN:-8192}"
export CUDA_DEVICE_ORDER="${CUDA_DEVICE_ORDER:-PCI_BUS_ID}"

# Experience / retriever services
export VDB_PORT="${VDB_PORT:-8007}"
export VDB_SERVER_URL="${VDB_SERVER_URL:-http://127.0.0.1:${VDB_PORT}}"
export VDB_AUTO_IMPORT="${VDB_AUTO_IMPORT:-0}"
export VDB_IMPORT_FORMAT="${VDB_IMPORT_FORMAT:-jsonl}"
export VDB_IMPORT_PRINCIPLES="${VDB_IMPORT_PRINCIPLES:-}"
export VDB_IMPORT_TRAJECTORIES="${VDB_IMPORT_TRAJECTORIES:-}"
export RETRIEVER_STUB_PORT="${RETRIEVER_STUB_PORT:-19999}"
export RETRIEVE_URL="${RETRIEVE_URL:-http://127.0.0.1:${RETRIEVER_STUB_PORT}/retrieve}"

# Training toggles and sensible defaults
export EVOLVER_KNOWLEDGE_SEARCH="${EVOLVER_KNOWLEDGE_SEARCH:-0}"
export EVOLVER_QA_OUTCOME="${EVOLVER_QA_OUTCOME:-0}"
export EVOLVER_REQUIRE_KNOWLEDGE_SEARCH="${EVOLVER_REQUIRE_KNOWLEDGE_SEARCH:-0}"
export USE_EXPERIENCE="${USE_EXPERIENCE:-true}"
export NGPUS_PER_NODE="${NGPUS_PER_NODE:-4}"
export TOTAL_EPOCHS="${TOTAL_EPOCHS:-5}"
export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-200}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-128}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-256}"
export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-8192}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-1024}"
export MAX_START_LENGTH="${MAX_START_LENGTH:-2048}"
export MAX_OBS_LENGTH="${MAX_OBS_LENGTH:-2048}"
export LR="${LR:-1e-6}"
export PPO_MINI_BATCH="${PPO_MINI_BATCH:-128}"
export PPO_MICRO_BATCH="${PPO_MICRO_BATCH:-32}"
export GEN_TP="${GEN_TP:-1}"
export GPU_MEM_UTIL="${GPU_MEM_UTIL:-0.4}"
export N_AGENT="${N_AGENT:-8}"
export SAVE_FREQ="${SAVE_FREQ:-10}"
export TEST_FREQ="${TEST_FREQ:-50}"
export RW_FORMAT="${RW_FORMAT:-0.05}"
export RW_EXPERIENCE="${RW_EXPERIENCE:-0.1}"
export VLLM_ATTENTION_BACKEND="${VLLM_ATTENTION_BACKEND:-XFORMERS}"
export MKL_SERVICE_FORCE_INTEL="${MKL_SERVICE_FORCE_INTEL:-1}"
export HYDRA_FULL_ERROR="${HYDRA_FULL_ERROR:-1}"
export TRAIN_CUDA_VISIBLE_DEVICES="${TRAIN_CUDA_VISIBLE_DEVICES:-0,1,2,3}"
